<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />

        <link href="/public/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/grid.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/smoothness/jquery-ui-1.10.3.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/slides.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="/public/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script type="text/javascript" src="/public/js/jquery.slides.min.js"></script>

        <title>Konzultace</title>
    </head>
    <body lang="cs">
        <div id="header">
            <div class="headerLeft">
                <div class="logo">
                    <a href="http://zs.zsnebusice.cz/">
                        Praha - Nebušice
                        <span></span>
                    </a>
                </div>
            </div>
            <div class="headerRight">
                <div class="image">
                </div>
            </div>

        </div>
            <div class="menu">
            {include menu.phtml}
        </div>

        <div id="content">

            {if !empty($flashMessage)}
            <section class="container_12">
                <div class="ad-notif-info grid_12"><p>{echo $flashMessage}</p></div>
            </section>
            {/if}

            <section class="container_12">
                {yield action}
            </section>

        </div>

        <script type="text/javascript" src="/public/js/global.js"></script>

    </body>
</html>
