<article class="grid_8">
    <h1>Přihlásit se</h1>
    <form method="post" action="#" class="stdform">
        <p>
            {if isset($account_error)}
            <span class="error">
                {echo $account_error}
            </span>
            {/if}
        </p>
        <p>
            <label>Email</label>
            <span class="field">
                <input style="width:250px;" type="email" name="email" class="mediuminput" required maxlength="60" />
            </span>
            {if isset($email_error)}
            <span class="error">
                {echo $email_error}
            </span>
            {/if}
        </p>
        <p>
            <label>Heslo</label>
            <span class="field">
                <input style="width:250px;" type="password" name="password" class="mediuminput" required maxlength="30" />
            </span>
            {if isset($password_error)}
            <span class="error">
                {echo $password_error}
            </span>
            {/if}
        </p>
        <p>
            <span class="field">
                <input style="width:250px;" type="submit" name="login" class="continue" value="Přihlásit" />
            </span>
        </p>

    </form>
</article>