<article class="grid_12">
    <div class="info"> 
        <h1>Seznam učitelů</h1>
        <h3>Vyberte učitele, se kterými máte zájem o konzultaci</h3>
    </div>
    <div class="grid_6">

        <form action="#" method="post">
            {if isset($errors["ucitError"])}
            <span class="error">
                {echo join("<br/>", $errors["ucitError"])}
            </span>
            {/if}
            <br/>
            <table>
                <tr>
                    <td>Jméno učitele</td>
                </tr>
                {foreach $ucitel in $ucitele}
                <tr>
                    <td>
                        <input type="checkbox" name="checkboxUcitele[]" id="checkboxUcitele_{echo $ucitel->id}" value="{echo $ucitel->id}"/>
                        <label for="checkboxUcitele_{echo $ucitel->id}">{echo $ucitel->firstname.' '.$ucitel->lastname}</label>                  
                    </td>
                </tr>
                {/foreach}

            </table>

            <input class="continue" type="submit" name="submitStepOne" value="Pokracovat" />
        </form>
    </div>
</article>


