<article class="grid_12">
    
        <div class="info"> 
        <h1>Váš časový rozvrh</h1>
    </div>
      <table class="finalTable">
        <tr>
        <td>Jméno učitele</td>
        <td>Čas</td>
            <center><td>Kabinet</td>
        </tr>
        {foreach $k in $konzultace}
        <tr>
            <td>{echo $k->firstname." ".$k->lastname}</td>
            <td>{echo $k->cas_start." - ".$k->cas_end}</td>
            <td>{echo $k->kabinet}</td>
        </tr>
        {/foreach}
    </table>
    
    <form method="post" action="#">
        <input class="back" type="submit" name="submitStepFour" value="Zrušit"  />
        <input class="back" type="button" name="print" value="Tisk" onclick="window.print();"/>
    </form>
    
</article>