<article class="grid_12">
    
    <table>
        <tr>
            <td>Jmeno ucitele</td>
            <td>Cas</td>
        </tr>
        {foreach $k in $konzultace}
        <tr>
            <td>{echo $k->firstname." ".$k->lastname}</td>
            <td>{echo $k->cas_start." - ".$k->cas_end}</td>
        </tr>
        {/foreach}
    </table>
    
    <form method="post" action="#">
        <input type="submit" name="subtmiStepThree" value="Potvrdit" />
        <input type="submit" name="subtmiStepThree" value="Zrusit" />
    </form>
</article>